version: "3"

services:

  app:
    image: registry.netlyt.io:5000/netlyt/flight_bot
    build:
      context: .
    ports:
      - 8801:5000
    restart: always
    env_file:
      - .env